# Generated by Django 2.2 on 2020-01-27 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='marketplace_id',
            field=models.TextField(default='ATVPDKIKX0DER', help_text='Defaults to US marketplace ID', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mws_auth_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='seller_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
